// MedGuide Offline - Drug Reference Database
// Educational reference only. Not for prescribing or individual treatment decisions.

var drugs = window.drugs = [
  {
    id: "metformin",
    genericName: "Metformin",
    brandNames: ["Glucophage", "Fortamet", "Glumetza"],
    drugClass: "Biguanide",
    therapeuticClass: "Antidiabetic",
    mechanismOfAction: "Decreases hepatic glucose production, decreases intestinal absorption of glucose, and improves insulin sensitivity by increasing peripheral glucose uptake and utilization.",
    indications: ["Type 2 diabetes mellitus", "Polycystic ovary syndrome (off-label in some regions)"],
    contraindications: ["Severe renal impairment (eGFR <30)", "Acute or chronic metabolic acidosis including diabetic ketoacidosis", "Known hypersensitivity"],
    adverseEffects: ["Gastrointestinal upset (nausea, diarrhea, abdominal discomfort)", "Vitamin B12 deficiency with long-term use", "Lactic acidosis (rare but serious)"],
    interactions: ["Iodinated contrast media (temporary discontinuation often recommended)", "Alcohol (increased risk of lactic acidosis)", "Certain drugs affecting renal function"],
    monitoring: ["Renal function (eGFR)", "Vitamin B12 levels periodically", "Glycemic control (HbA1c, glucose)"],
    specialPopulations: "Use caution in elderly; dose adjust for renal function. Generally avoided in significant hepatic impairment. Pregnancy category considerations vary by region—consult local guidance.",
    counseling: "Take with meals to reduce GI effects. Do not crush extended-release formulations. Report unexplained muscle pain, difficulty breathing, or severe fatigue."
  },
  {
    id: "lisinopril",
    genericName: "Lisinopril",
    brandNames: ["Prinivil", "Zestril"],
    drugClass: "ACE inhibitor",
    therapeuticClass: "Antihypertensive / Heart failure agent",
    mechanismOfAction: "Inhibits angiotensin-converting enzyme, reducing formation of angiotensin II, leading to vasodilation, reduced aldosterone secretion, and decreased blood pressure and afterload.",
    indications: ["Hypertension", "Heart failure", "Post-myocardial infarction", "Diabetic nephropathy (selected cases)"],
    contraindications: ["History of ACE inhibitor-induced angioedema", "Bilateral renal artery stenosis", "Pregnancy", "Hypersensitivity"],
    adverseEffects: ["Dry cough", "Hyperkalemia", "Hypotension", "Angioedema (rare but serious)", "Elevated creatinine", "Dizziness"],
    interactions: ["Potassium-sparing diuretics or potassium supplements (hyperkalemia risk)", "NSAIDs (may reduce antihypertensive effect and worsen renal function)", "Lithium (increased lithium levels)"],
    monitoring: ["Blood pressure", "Serum potassium", "Renal function (creatinine, eGFR)"],
    specialPopulations: "Contraindicated in pregnancy. Dose adjustment may be needed in renal impairment. Use caution in volume-depleted patients.",
    counseling: "Rise slowly from sitting/lying to reduce dizziness. Report swelling of face, lips, or tongue immediately. Do not use potassium supplements without advice."
  },
  {
    id: "atorvastatin",
    genericName: "Atorvastatin",
    brandNames: ["Lipitor"],
    drugClass: "HMG-CoA reductase inhibitor (Statin)",
    therapeuticClass: "Lipid-lowering agent",
    mechanismOfAction: "Competitively inhibits HMG-CoA reductase, the rate-limiting enzyme in cholesterol biosynthesis, leading to increased LDL receptor expression and reduced circulating LDL cholesterol.",
    indications: ["Hypercholesterolemia", "Mixed dyslipidemia", "Prevention of cardiovascular events in high-risk patients"],
    contraindications: ["Active liver disease", "Unexplained persistent elevations of hepatic transaminases", "Pregnancy", "Hypersensitivity"],
    adverseEffects: ["Myalgia", "Elevated liver enzymes", "Rare: myopathy/rhabdomyolysis", "Gastrointestinal symptoms", "Headache"],
    interactions: ["Strong CYP3A4 inhibitors (e.g., certain antifungals, macrolides) increase atorvastatin levels", "Grapefruit juice (in large amounts)", "Gemfibrozil and other fibrates (myopathy risk)"],
    monitoring: ["Lipid panel", "Liver enzymes (baseline and as indicated)", "Symptoms of muscle toxicity"],
    specialPopulations: "Contraindicated in pregnancy and breastfeeding. Dose adjustments may be needed with certain interacting drugs or in hepatic impairment.",
    counseling: "Report unexplained muscle pain, tenderness, or weakness, especially if accompanied by fever or dark urine. Take consistently; evening dosing not strictly required for atorvastatin."
  },
  {
    id: "albuterol",
    genericName: "Albuterol (Salbutamol)",
    brandNames: ["Ventolin", "ProAir", "Proventil"],
    drugClass: "Short-acting beta-2 agonist (SABA)",
    therapeuticClass: "Bronchodilator",
    mechanismOfAction: "Selectively stimulates beta-2 adrenergic receptors in bronchial smooth muscle, causing relaxation and bronchodilation.",
    indications: ["Acute relief of bronchospasm in asthma and COPD", "Prevention of exercise-induced bronchospasm"],
    contraindications: ["Known hypersensitivity to albuterol or components"],
    adverseEffects: ["Tremor", "Tachycardia", "Palpitations", "Nervousness", "Headache", "Hypokalemia (with high doses)"],
    interactions: ["Beta blockers (may antagonize effect)", "Other sympathomimetics (additive effects)", "Diuretics (hypokalemia risk)"],
    monitoring: ["Frequency of use (overuse may indicate poor control)", "Heart rate in sensitive patients", "Potassium with frequent high-dose use"],
    specialPopulations: "Use caution in patients with cardiovascular disease, hyperthyroidism, or diabetes. Pediatric and geriatric dosing considerations apply.",
    counseling: "Use as directed for rescue. If needing more frequent doses, seek medical review. Proper inhaler technique is essential. Rinse mouth after use if using with corticosteroid inhaler."
  },
  {
    id: "omeprazole",
    genericName: "Omeprazole",
    brandNames: ["Prilosec", "Losec"],
    drugClass: "Proton pump inhibitor (PPI)",
    therapeuticClass: "Antiulcer / Antisecretory",
    mechanismOfAction: "Irreversibly inhibits the H+/K+-ATPase (proton pump) in gastric parietal cells, suppressing both basal and stimulated acid secretion.",
    indications: ["GERD", "Peptic ulcer disease", "Eradication of H. pylori (as part of combination regimens)", "Zollinger-Ellison syndrome", "Prevention of NSAID-associated ulcers"],
    contraindications: ["Known hypersensitivity to omeprazole or other PPIs"],
    adverseEffects: ["Headache", "Diarrhea", "Abdominal pain", "Nausea", "Long-term: potential nutrient deficiencies (B12, magnesium), increased infection risk, bone effects"],
    interactions: ["Clopidogrel (possible reduced antiplatelet effect with some PPIs)", "Drugs requiring acidic pH for absorption (e.g., certain antifungals, iron)", "CYP2C19 substrates"],
    monitoring: ["Symptom response", "Magnesium levels with prolonged use if indicated", "Bone health considerations with long-term therapy"],
    specialPopulations: "Generally considered acceptable in pregnancy when clearly needed (local guidance varies). Dose adjustment may be needed in severe hepatic impairment.",
    counseling: "Take before meals. Swallow whole; do not crush delayed-release capsules. Long-term use should be reviewed periodically with a clinician."
  },
  {
    id: "sertraline",
    genericName: "Sertraline",
    brandNames: ["Zoloft"],
    drugClass: "Selective serotonin reuptake inhibitor (SSRI)",
    therapeuticClass: "Antidepressant",
    mechanismOfAction: "Selectively inhibits the reuptake of serotonin (5-HT) at the presynaptic membrane, increasing serotonergic neurotransmission.",
    indications: ["Major depressive disorder", "Obsessive-compulsive disorder", "Panic disorder", "Social anxiety disorder", "Post-traumatic stress disorder", "Premenstrual dysphoric disorder"],
    contraindications: ["Concurrent use with MAOIs or within 14 days", "Concurrent use with pimozide", "Known hypersensitivity"],
    adverseEffects: ["Nausea", "Diarrhea", "Insomnia or somnolence", "Sexual dysfunction", "Dry mouth", "Increased risk of suicidal thinking in young people (boxed warning)", "Serotonin syndrome (rare)"],
    interactions: ["MAOIs (contraindicated)", "Other serotonergic drugs (serotonin syndrome risk)", "Drugs affecting CYP2D6 or CYP3A4", "NSAIDs/aspirin (bleeding risk)"],
    monitoring: ["Mood and suicidality especially early in treatment", "Symptoms of serotonin syndrome", "Sodium in elderly or volume-depleted patients"],
    specialPopulations: "Black box warning for increased suicidal ideation in children, adolescents, and young adults. Use caution in pregnancy and breastfeeding—risk-benefit discussion required.",
    counseling: "May take several weeks for full effect. Do not stop abruptly. Report worsening mood, agitation, or suicidal thoughts immediately. Avoid alcohol."
  },
  {
    id: "ibuprofen",
    genericName: "Ibuprofen",
    brandNames: ["Advil", "Motrin", "Nurofen"],
    drugClass: "Nonsteroidal anti-inflammatory drug (NSAID)",
    therapeuticClass: "Analgesic / Anti-inflammatory / Antipyretic",
    mechanismOfAction: "Inhibits cyclooxygenase (COX-1 and COX-2) enzymes, reducing prostaglandin synthesis, thereby decreasing pain, inflammation, and fever.",
    indications: ["Mild to moderate pain", "Inflammation (e.g., arthritis, soft tissue injury)", "Fever", "Dysmenorrhea"],
    contraindications: ["History of NSAID-induced asthma, urticaria, or allergic-type reaction", "Perioperative pain in CABG surgery", "Active peptic ulcer or GI bleeding", "Severe heart failure (in some contexts)", "Third trimester of pregnancy"],
    adverseEffects: ["Gastrointestinal irritation, ulceration, bleeding", "Increased cardiovascular risk with prolonged use", "Renal impairment", "Elevated blood pressure", "Fluid retention"],
    interactions: ["Anticoagulants and antiplatelets (bleeding risk)", "ACE inhibitors/ARBs and diuretics (renal risk)", "Lithium", "Methotrexate"],
    monitoring: ["Renal function with prolonged use or risk factors", "Blood pressure", "Signs of GI bleeding"],
    specialPopulations: "Avoid in third trimester. Use lowest effective dose for shortest duration, especially in elderly and those with cardiovascular or renal disease.",
    counseling: "Take with food or milk. Do not exceed recommended dose. Seek care for black stools, severe abdominal pain, or unexplained swelling."
  },
  {
    id: "levothyroxine",
    genericName: "Levothyroxine",
    brandNames: ["Synthroid", "Levoxyl", "Euthyrox"],
    drugClass: "Thyroid hormone",
    therapeuticClass: "Thyroid replacement",
    mechanismOfAction: "Synthetic form of thyroxine (T4) that is converted to active triiodothyronine (T3) in peripheral tissues, regulating metabolism, growth, and development.",
    indications: ["Hypothyroidism", "TSH suppression in selected thyroid conditions"],
    contraindications: ["Untreated thyrotoxicosis", "Acute myocardial infarction (relative in some cases)", "Uncorrected adrenal insufficiency"],
    adverseEffects: ["Symptoms of over-replacement: palpitations, anxiety, weight loss, insomnia, heat intolerance", "Rare: allergic reactions to inactive ingredients"],
    interactions: ["Absorption reduced by calcium, iron, antacids, PPIs, bile acid sequestrants", "May affect warfarin requirements", "Estrogens may increase requirements"],
    monitoring: ["TSH and free T4", "Clinical symptoms of hypo- or hyperthyroidism", "Heart rate and rhythm in susceptible patients"],
    specialPopulations: "Dose requirements change in pregnancy—close monitoring essential. Elderly and those with cardiac disease start low and titrate slowly.",
    counseling: "Take on empty stomach, typically 30–60 minutes before breakfast, consistently. Separate from interacting supplements/medications by several hours. Do not switch brands without advice if possible."
  },
  {
    id: "amlodipine",
    genericName: "Amlodipine",
    brandNames: ["Norvasc"],
    drugClass: "Dihydropyridine calcium channel blocker",
    therapeuticClass: "Antihypertensive / Antianginal",
    mechanismOfAction: "Inhibits calcium ion influx across cell membranes in vascular smooth muscle and cardiac muscle, causing peripheral arterial vasodilation and reduced peripheral vascular resistance.",
    indications: ["Hypertension", "Chronic stable angina", "Vasospastic angina"],
    contraindications: ["Known hypersensitivity to amlodipine or dihydropyridines"],
    adverseEffects: ["Peripheral edema", "Flushing", "Headache", "Dizziness", "Palpitations", "Fatigue"],
    interactions: ["Strong CYP3A4 inhibitors may increase levels", "Simvastatin (dose limit recommended with amlodipine)"],
    monitoring: ["Blood pressure", "Heart rate", "Edema"],
    specialPopulations: "Generally well tolerated in elderly; start at lower doses. Hepatic impairment may require dose reduction.",
    counseling: "May cause ankle swelling; report significant edema. Rise slowly if dizzy. Consistent daily use is important for blood pressure control."
  },
  {
    id: "metoprolol",
    genericName: "Metoprolol",
    brandNames: ["Lopressor", "Toprol-XL"],
    drugClass: "Selective beta-1 blocker",
    therapeuticClass: "Antihypertensive / Antianginal / Heart failure agent",
    mechanismOfAction: "Selectively blocks beta-1 adrenergic receptors, reducing heart rate, contractility, and blood pressure; also reduces renin release.",
    indications: ["Hypertension", "Angina", "Heart failure (extended-release)", "Post-myocardial infarction", "Rate control in atrial fibrillation"],
    contraindications: ["Severe bradycardia", "Second- or third-degree heart block (without pacemaker)", "Cardiogenic shock", "Decompensated heart failure", "Sick sinus syndrome"],
    adverseEffects: ["Bradycardia", "Fatigue", "Dizziness", "Depression", "Cold extremities", "Sexual dysfunction", "Bronchospasm (less with selective agents but still possible)"],
    interactions: ["Other drugs slowing heart rate or AV conduction", "CYP2D6 inhibitors may increase levels", "Clonidine (rebound hypertension risk if stopped abruptly together)"],
    monitoring: ["Heart rate and blood pressure", "Signs of heart failure decompensation", "Blood glucose in diabetics (may mask hypoglycemia)"],
    specialPopulations: "Use caution in asthma/COPD. Abrupt withdrawal can cause rebound. Dose adjust in hepatic impairment.",
    counseling: "Do not stop suddenly. Take consistently. Report very slow heart rate, severe fatigue, or worsening shortness of breath."
  },
  {
    id: "sumatriptan",
    genericName: "Sumatriptan",
    brandNames: ["Imitrex", "Imigran"],
    drugClass: "Serotonin 5-HT1B/1D receptor agonist (Triptan)",
    therapeuticClass: "Antimigraine",
    mechanismOfAction: "Agonist at 5-HT1B/1D receptors on intracranial blood vessels and sensory nerves of the trigeminal system, causing vasoconstriction and inhibition of neuropeptide release.",
    indications: ["Acute treatment of migraine with or without aura"],
    contraindications: ["History of ischemic heart disease, stroke, TIA, or peripheral vascular disease", "Uncontrolled hypertension", "Hemiplegic or basilar migraine", "Use within 24 hours of another triptan or ergotamine", "Concurrent MAOI use"],
    adverseEffects: ["Sensation of pressure or tightness in chest/throat/neck", "Flushing", "Dizziness", "Paresthesias", "Injection site reactions (if injectable)"],
    interactions: ["Ergot derivatives and other triptans (additive vasoconstriction)", "SSRIs/SNRIs (serotonin syndrome risk, though uncommon)", "MAOIs"],
    monitoring: ["Frequency of use (medication-overuse headache risk)", "Cardiovascular symptoms"],
    specialPopulations: "Not for prevention. Use caution in patients with risk factors for coronary artery disease. Safety in pregnancy not fully established.",
    counseling: "Use at onset of migraine. Do not use for other types of headache. Seek emergency care for severe chest pain or neurological changes. Limit frequency of use."
  },
  {
    id: "amoxicillin",
    genericName: "Amoxicillin",
    brandNames: ["Amoxil", "Moxatag"],
    drugClass: "Aminopenicillin antibiotic",
    therapeuticClass: "Antibiotic",
    mechanismOfAction: "Inhibits bacterial cell wall synthesis by binding to penicillin-binding proteins, leading to cell lysis in susceptible organisms.",
    indications: ["Various bacterial infections including respiratory tract, ear, urinary tract, skin, and H. pylori regimens (as part of combination)"],
    contraindications: ["History of serious hypersensitivity reaction to amoxicillin or other beta-lactams"],
    adverseEffects: ["Diarrhea", "Nausea", "Rash", "Allergic reactions including anaphylaxis", "Clostridioides difficile-associated diarrhea"],
    interactions: ["May reduce efficacy of oral contraceptives (advise backup method)", "Probenecid increases levels", "Allopurinol may increase rash risk"],
    monitoring: ["Clinical response", "Signs of allergic reaction or superinfection"],
    specialPopulations: "Dose adjust in severe renal impairment. Generally considered compatible with pregnancy when indicated.",
    counseling: "Complete the full course even if feeling better. Take with or without food. Report severe diarrhea or rash promptly. Shake suspensions well."
  },
  {
    id: "prednisone",
    genericName: "Prednisone",
    brandNames: ["Deltasone", "Rayos"],
    drugClass: "Systemic corticosteroid",
    therapeuticClass: "Anti-inflammatory / Immunosuppressant",
    mechanismOfAction: "Binds to glucocorticoid receptors, modulating gene expression to produce anti-inflammatory and immunosuppressive effects; also has mineralocorticoid activity.",
    indications: ["Inflammatory and autoimmune conditions", "Allergic disorders", "Asthma exacerbations", "Certain hematologic disorders", "Replacement therapy in adrenal insufficiency (with mineralocorticoid)"],
    contraindications: ["Systemic fungal infections (relative)", "Known hypersensitivity", "Live vaccines in high-dose immunosuppressive regimens"],
    adverseEffects: ["Short-term: elevated glucose, mood changes, insomnia, increased appetite, fluid retention", "Long-term: osteoporosis, adrenal suppression, Cushingoid features, infection risk, hypertension, cataracts"],
    interactions: ["CYP3A4 inducers/inhibitors affect levels", "NSAIDs increase GI risk", "May antagonize effects of antidiabetics and antihypertensives"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density with prolonged use", "Signs of infection", "Adrenal function if tapering after long courses"],
    specialPopulations: "Taper after prolonged use. Use lowest effective dose. Special caution in diabetes, hypertension, osteoporosis, and psychiatric history.",
    counseling: "Take with food. Do not stop abruptly after more than a few days of use. Report signs of infection, significant mood change, or unusual swelling. Carry medical alert if on long-term therapy."
  },
  {
    id: "gabapentin",
    genericName: "Gabapentin",
    brandNames: ["Neurontin", "Gralise"],
    drugClass: "Gabapentinoid",
    therapeuticClass: "Anticonvulsant / Neuropathic pain agent",
    mechanismOfAction: "Binds to the α2δ subunit of voltage-gated calcium channels in the CNS, modulating neurotransmitter release; exact mechanism for analgesic and antiseizure effects not fully elucidated.",
    indications: ["Partial seizures (adjunctive)", "Postherpetic neuralgia", "Neuropathic pain (various off-label uses)"],
    contraindications: ["Known hypersensitivity to gabapentin"],
    adverseEffects: ["Dizziness", "Somnolence", "Peripheral edema", "Ataxia", "Fatigue", "Weight gain", "Mood changes"],
    interactions: ["CNS depressants (additive sedation)", "Antacids may reduce absorption if taken together"],
    monitoring: ["Seizure control or pain response", "Mood and suicidal ideation", "Renal function (dose adjustment required)"],
    specialPopulations: "Dose must be adjusted in renal impairment. Increased risk of respiratory depression when combined with opioids. Caution in elderly.",
    counseling: "May cause drowsiness—avoid driving until effects known. Do not stop suddenly. Report new or worsening depression or suicidal thoughts. Separate from antacids by 2 hours."
  },
  {
    id: "furosemide",
    genericName: "Furosemide",
    brandNames: ["Lasix"],
    drugClass: "Loop diuretic",
    therapeuticClass: "Diuretic",
    mechanismOfAction: "Inhibits the Na-K-2Cl cotransporter in the thick ascending limb of the loop of Henle, increasing excretion of sodium, chloride, potassium, and water.",
    indications: ["Edema associated with heart failure, liver cirrhosis, or renal disease", "Hypertension (often in combination)", "Acute pulmonary edema"],
    contraindications: ["Anuria", "Known hypersensitivity to furosemide or sulfonamides (cross-reactivity possible)"],
    adverseEffects: ["Electrolyte disturbances (hypokalemia, hyponatremia, hypomagnesemia)", "Dehydration", "Hypotension", "Ototoxicity (especially high doses or rapid IV)", "Hyperuricemia", "Glucose intolerance"],
    interactions: ["Aminoglycosides (ototoxicity/nephrotoxicity risk)", "Lithium (increased levels)", "NSAIDs (may reduce diuretic effect)", "Digoxin (hypokalemia increases toxicity risk)"],
    monitoring: ["Electrolytes", "Renal function", "Volume status", "Blood pressure", "Hearing with high-dose therapy"],
    specialPopulations: "Close monitoring needed in elderly and those with renal or hepatic impairment. May require potassium supplementation.",
    counseling: "Take in morning to avoid nocturia. Report muscle cramps, extreme thirst, dizziness, or hearing changes. Maintain adequate fluid intake unless restricted."
  },
  {
    id: "clopidogrel",
    genericName: "Clopidogrel",
    brandNames: ["Plavix"],
    drugClass: "P2Y12 inhibitor (Thienopyridine)",
    therapeuticClass: "Antiplatelet",
    mechanismOfAction: "Prodrug that irreversibly inhibits the P2Y12 ADP receptor on platelets, preventing activation of the GPIIb/IIIa complex and reducing platelet aggregation.",
    indications: ["Acute coronary syndromes", "Secondary prevention after MI, stroke, or peripheral arterial disease", "Post-stent placement"],
    contraindications: ["Active pathological bleeding", "Known hypersensitivity"],
    adverseEffects: ["Bleeding", "Bruising", "Rare: thrombotic thrombocytopenic purpura", "Gastrointestinal upset"],
    interactions: ["CYP2C19 inhibitors (e.g., some PPIs) may reduce activation", "Other antiplatelets/anticoagulants (increased bleeding)", "NSAIDs (bleeding risk)"],
    monitoring: ["Signs of bleeding", "Complete blood count if indicated", "Clinical ischemic events"],
    specialPopulations: "Genetic variation in CYP2C19 affects response. Use caution in patients at high bleeding risk. Discontinue before elective surgery as advised.",
    counseling: "Report unusual bleeding or bruising. Do not stop without medical advice after stent placement. Inform all providers and dentists that you are taking this medication."
  },
  {
    id: "montelukast",
    genericName: "Montelukast",
    brandNames: ["Singulair"],
    drugClass: "Leukotriene receptor antagonist",
    therapeuticClass: "Asthma / Allergy controller",
    mechanismOfAction: "Selectively blocks the cysteinyl leukotriene receptor (CysLT1), inhibiting the effects of leukotrienes that contribute to airway edema, smooth muscle contraction, and inflammation.",
    indications: ["Asthma (maintenance)", "Exercise-induced bronchoconstriction", "Allergic rhinitis"],
    contraindications: ["Known hypersensitivity"],
    adverseEffects: ["Headache", "Abdominal pain", "Upper respiratory infection symptoms", "Neuropsychiatric events (agitation, depression, suicidal thoughts—boxed warning)"],
    interactions: ["Generally few clinically significant interactions; phenobarbital and rifampin may reduce levels"],
    monitoring: ["Asthma control", "Mood and behavior changes"],
    specialPopulations: "Boxed warning regarding serious neuropsychiatric events. Not for acute asthma attacks. Use in pregnancy only if clearly needed.",
    counseling: "Take regularly for prevention, not for acute relief. Report any changes in mood, behavior, or suicidal thoughts immediately. Chewable tablets should be chewed thoroughly."
  },
  {
    id: "warfarin",
    genericName: "Warfarin",
    brandNames: ["Coumadin", "Jantoven"],
    drugClass: "Vitamin K antagonist",
    therapeuticClass: "Anticoagulant",
    mechanismOfAction: "Inhibits vitamin K epoxide reductase, depleting vitamin K-dependent clotting factors (II, VII, IX, X) and proteins C and S, thereby impairing coagulation.",
    indications: ["Prevention and treatment of venous thromboembolism", "Prevention of systemic embolism in atrial fibrillation and after heart valve replacement"],
    contraindications: ["Active bleeding", "Severe uncontrolled hypertension", "Pregnancy (except selected mechanical valves with careful management)", "Recent or planned surgery with high bleeding risk"],
    adverseEffects: ["Bleeding (any site)", "Skin necrosis (rare, early)", "Purple toe syndrome", "Drug and dietary interactions numerous"],
    interactions: ["Many drugs (antibiotics, antifungals, amiodarone, etc.)", "Vitamin K-rich foods", "Alcohol", "Herbal products"],
    monitoring: ["INR regularly", "Signs of bleeding or thrombosis", "Complete blood count periodically"],
    specialPopulations: "Highly individualized dosing. Significant interactions and narrow therapeutic index. Antidote is vitamin K; urgent reversal protocols exist.",
    counseling: "Consistent diet regarding vitamin K. Report any bleeding. Inform all providers. Regular INR testing is mandatory. Carry identification indicating anticoagulant use."
  },
  {
    id: "insulin-glargine",
    genericName: "Insulin glargine",
    brandNames: ["Lantus", "Basaglar", "Toujeo"],
    drugClass: "Long-acting insulin analog",
    therapeuticClass: "Antidiabetic / Insulin",
    mechanismOfAction: "Binds to insulin receptors, facilitating cellular uptake of glucose, inhibiting hepatic glucose production, and promoting storage of glucose as glycogen; provides relatively peakless basal coverage.",
    indications: ["Type 1 diabetes", "Type 2 diabetes requiring basal insulin"],
    contraindications: ["Hypoglycemia", "Hypersensitivity to insulin glargine"],
    adverseEffects: ["Hypoglycemia", "Weight gain", "Injection site reactions", "Lipodystrophy", "Hypokalemia"],
    interactions: ["Other antidiabetic agents (additive hypoglycemia risk)", "Corticosteroids, thiazides (may increase requirements)", "Beta blockers (may mask hypoglycemia symptoms)"],
    monitoring: ["Blood glucose", "HbA1c", "Injection sites", "Hypoglycemia symptoms and frequency"],
    specialPopulations: "Dosing highly individualized. Never share pens. Adjustments needed with changes in diet, activity, illness, or renal/hepatic function.",
    counseling: "Rotate injection sites. Never mix with other insulins in the same syringe (for most formulations). Recognize and treat hypoglycemia promptly. Store properly; do not freeze."
  },
  {
    id: "cetirizine",
    genericName: "Cetirizine",
    brandNames: ["Zyrtec"],
    drugClass: "Second-generation H1 antihistamine",
    therapeuticClass: "Antihistamine / Antiallergic",
    mechanismOfAction: "Selectively antagonizes peripheral H1 receptors, reducing allergic symptoms mediated by histamine without significant CNS penetration at usual doses.",
    indications: ["Allergic rhinitis", "Chronic urticaria", "Allergic conjunctivitis symptoms"],
    contraindications: ["Known hypersensitivity to cetirizine or hydroxyzine"],
    adverseEffects: ["Somnolence (less than first-generation but still possible)", "Dry mouth", "Fatigue", "Headache"],
    interactions: ["CNS depressants (additive sedation)", "Theophylline may slightly reduce clearance"],
    monitoring: ["Symptom control", "Sedation especially when starting therapy"],
    specialPopulations: "Dose reduce in significant renal impairment. Generally preferred over first-generation agents in elderly due to less anticholinergic effect.",
    counseling: "May cause drowsiness in some people—test response before driving. Take once daily. For allergic rhinitis, regular use during season is often more effective than as-needed."
  }
];
